server:
  port: 80
  servlet:
    context-path: /NadyaClothing
spring:
  datasource:
    password: Oo046746!
    url: jdbc:mysql://localhost:3306/nadya_clothing_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 223311024256-iu50oq6q42qnrm04easr7p9j4p3ko050.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 515565180167245
            client-secret: 30b5c2d1f34d0c5daf50e32f034ff558
            scope:
            - email
            - public_profile
       
  spring:
    main:
      allow-circular-references: true
                  